### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1111: character maps to <undefined>

### ISSUE THREAD

**Issue by fassad-almaviva** [Almaviva-do-Brasil/firstpctpypi#1]
on execute python setup.py sdist powershell show:

Traceback (most recent call last):
  File "setup.py", line 15, in <module>
    readme = fh.read()
  File "C:\Python\Python38-32\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1111: character maps to <undefined>

**Comment by fassad-almaviva** [comment]
add
```
encoding="utf8"
```

at
```
with open (
    file="README.md"
,   mode="r"
,   encoding="utf8"     # fassad, 2021-08-30: fix issue #1 on version 0.0.2
) as fh:
    readme = fh.read()
```
